In [64]:
import pandas as pd

# Data Preprocessing

In [65]:
mvp_df = pd.read_csv("data/nba_mvp_voting_2010_to_2025.csv")
standings_df = pd.read_csv("data/nba_standings_2010_to_2025.csv")

In [66]:
# Remove Columns not needed for analysis and rename
mvp_df = mvp_df.drop(columns=["Rank", "Age", "First", "Pts Won", "Pts Max", "WS/48"], errors='ignore')
mvp_df = mvp_df.rename(columns={"Tm": "Team"})
standings_df = standings_df.drop(columns=["W", "L", "PS/G", "PA/G", "SRS", "GB", "Conference"], errors='ignore')

In [67]:
# Map old team abbreviations to new ones
team_abbrev = {
    "NOH": "NOP",
    "CHA": "CHO",
}

mvp_df["Team"] = mvp_df["Team"].replace(team_abbrev)
mvp_df

,Season,Player,Team,Share,G,MP,PTS,TRB,AST,STL,BLK,FG%,3P%,FT%,WS
0,2009-10,LeBron James,CLE,0.980,76,39.0,29.7,7.3,8.6,1.6,1.0,0.503,0.333,0.767,18.5
1,2009-10,Kevin Durant,OKC,0.495,82,39.5,30.1,7.6,2.8,1.4,1.0,0.476,0.365,0.900,16.1
2,2009-10,Kobe Bryant,LAL,0.487,73,38.8,27.0,5.4,5.0,1.5,0.3,0.456,0.329,0.811,9.4
3,2009-10,Dwight Howard,ORL,0.389,82,34.7,18.3,13.2,1.8,0.9,2.8,0.612,0.000,0.592,13.2
4,2009-10,Dwyane Wade,MIA,0.097,77,36.3,26.6,4.8,6.5,1.8,1.1,0.476,0.300,0.761,13.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
202,2024-25,Anthony Edwards,MIN,0.012,79,36.3,27.6,5.7,4.5,1.2,0.6,0.447,0.395,0.837,8.4
203,2024-25,Stephen Curry,GSW,0.002,70,32.2,24.5,4.4,6.0,1.1,0.4,0.448,0.397,0.933,7.9
204,2024-25,Jalen Brunson,NYK,0.001,65,35.4,26.0,2.9,7.3,0.9,0.1,0.488,0.383,0.821,8.3
205,2024-25,James Harden,LAC,0.001,79,35.3,22.8,5.8,8.7,1.5,0.7,0.410,0.352,0.874,8.3
206,2024-25,Evan Mobley,CLE,0.001,71,30.5,18.5,9.3,3.2,0.9,1.6,0.557,0.370,0.725,9.0

In [68]:
# Map team full name to abbreviations in standings_df
team_full_to_abbrev = {
    "Atlanta Hawks": "ATL",
    "Boston Celtics": "BOS",
    "Brooklyn Nets": "BRK",
    "New Jersey Nets": "BRK",
    "Charlotte Hornets": "CHO",
    "Charlotte Bobcats": "CHO",
    "Chicago Bulls": "CHI",
    "Cleveland Cavaliers": "CLE",
    "Dallas Mavericks": "DAL",
    "Denver Nuggets": "DEN",
    "Detroit Pistons": "DET",
    "Golden State Warriors": "GSW",
    "Houston Rockets": "HOU",
    "Indiana Pacers": "IND",
    "Los Angeles Clippers": "LAC",
    "Los Angeles Lakers": "LAL",
    "Memphis Grizzlies": "MEM",
    "Miami Heat": "MIA",
    "Milwaukee Bucks": "MIL",
    "Minnesota Timberwolves": "MIN",
    "New Orleans Pelicans": "NOP",
    "New Orleans Hornets": "NOP",
    "New York Knicks": "NYK",
    "Oklahoma City Thunder": "OKC",
    "Orlando Magic": "ORL",
    "Philadelphia 76ers": "PHI",
    "Phoenix Suns": "PHX",
    "Portland Trail Blazers": "POR",
    "Sacramento Kings": "SAC",
    "San Antonio Spurs": "SAS",
    "Toronto Raptors": "TOR",
    "Utah Jazz": "UTA",
    "Washington Wizards": "WAS"
}

standings_df['Team'] = standings_df['Team'].map(team_full_to_abbrev)
standings_df

      Season Team   W/L%
0    2009-10  BOS  0.610
1    2009-10  TOR  0.488
2    2009-10  NYK  0.354
3    2009-10  PHI  0.329
4    2009-10  BRK  0.146
..       ...  ...    ...
475  2024-25  PHX  0.439
476  2024-25  POR  0.439
477  2024-25  SAS  0.415
478  2024-25  NOP  0.256
479  2024-25  UTA  0.207

[480 rows x 3 columns]

In [69]:
# Add W/L% to MVP data
df = pd.merge(mvp_df, standings_df, on=["Season", "Team"], how='left')
df

,Season,Player,Team,Share,G,MP,PTS,TRB,AST,STL,BLK,FG%,3P%,FT%,WS,W/L%
0,2009-10,LeBron James,CLE,0.980,76,39.0,29.7,7.3,8.6,1.6,1.0,0.503,0.333,0.767,18.5,0.744
1,2009-10,Kevin Durant,OKC,0.495,82,39.5,30.1,7.6,2.8,1.4,1.0,0.476,0.365,0.900,16.1,0.610
2,2009-10,Kobe Bryant,LAL,0.487,73,38.8,27.0,5.4,5.0,1.5,0.3,0.456,0.329,0.811,9.4,0.695
3,2009-10,Dwight Howard,ORL,0.389,82,34.7,18.3,13.2,1.8,0.9,2.8,0.612,0.000,0.592,13.2,0.720
4,2009-10,Dwyane Wade,MIA,0.097,77,36.3,26.6,4.8,6.5,1.8,1.1,0.476,0.300,0.761,13.0,0.573
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
202,2024-25,Anthony Edwards,MIN,0.012,79,36.3,27.6,5.7,4.5,1.2,0.6,0.447,0.395,0.837,8.4,0.598
203,2024-25,Stephen Curry,GSW,0.002,70,32.2,24.5,4.4,6.0,1.1,0.4,0.448,0.397,0.933,7.9,0.585
204,2024-25,Jalen Brunson,NYK,0.001,65,35.4,26.0,2.9,7.3,0.9,0.1,0.488,0.383,0.821,8.3,0.622
205,2024-25,James Harden,LAC,0.001,79,35.3,22.8,5.8,8.7,1.5,0.7,0.410,0.352,0.874,8.3,0.610
206,2024-25,Evan Mobley,CLE,0.001,71,30.5,18.5,9.3,3.2,0.9,1.6,0.557,0.370,0.725,9.0,0.780

In [ ]:
# Create X_train and Y_train datasets